// Sqwod Daily — podcast show links + feed.
// Once the show is live on Apple/Spotify, paste the real show URLs here and the
// "Listen on" buttons across the site update everywhere at once.
export const APPLE_URL = '#';
export const SPOTIFY_URL = '#';

// RSS feeds are auto-generated by automation/audio.mjs (EN + DE).
export const rssFor = (lang: string) => (lang === 'de' ? '/podcast.de.xml' : '/podcast.xml');

// Per-episode audio file path, written by automation/audio.mjs.
export const episodeAudio = (date: string, lang: string) => `/audio/${date}-${lang}.mp3`;
